<?php /* * *******************************************************************
  The MIT License (MIT)

  Copyright (c) 2018 Intuz

  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * ******************************************************************* */ ?>
<?php

$mess = array("login" => "You have logged in successfully.",
    "del" => "Record has been deleted successfully.",
    "add" => "Record has been added successfully.",
    "edit" => "Record has been updated successfully.",
    "logout" => "<span class='success-message'>You have logged out successfully.</span>",
    "logfirst" => "Please, Login first.",
    "invalid" => "<span class='error-message'>Invalid Username / Password.</span>",
    "invaliduser" => "<span class='error-message'>Username does not exist. Please try again.</span>",
    "sessionexpire" => "<span class='error-message'>Your session is expired. Please login to access admin.</span>",
    "filedel" => "System removed file.",
    "nochpass" => "You have entered wrong password. Please try again",
    "chpass" => "Your password has been changed successfully.",
    "setsave" => "Settings has been changed successfully.",
    "sameuser" => "Username/email already exists.",
    "wrongzip" => "You have entered wrong Zipcode.",
    "merchantuser" => "User already has a venue page.",
    "reg" => "Thank you for registering with us. Please check your email for confirmation email.",
    "passsent" => "<span class='success-message'>Your password has been sent to your email address.</span>",
    "emailnotexist" => "<span class='error-message'>E-Mail address does not exist. Please try again.</span>",
    "invpwd" => "Current Password you entered is wrong, Please try again!",
    "emailsent" => "Thank you! System sent your enquiry has been to administrator.",
    "orsentdel" => "System sent the order. System deleted member from database.",
    "reviewadd" => "Thank You! System submitted your review.",
    "csvuploaded" => "System uploaded order CSV successfully.",
    "categoryexist" => "Category already exists.",
    "bannerexist" => "Banner with same title already exists.",
    "file_import_fail" => "Error in file import. Please try again.",
    "notexcel" => "Please upload .xls or .xlsx files only.",
    "addimg" => "Image uploaded successfully.",
    "delimg" => "Image deleted successfully.",
    "active" => "Record has been activated successfully.",
    "inactive" => "Record has been inactivated successfully.",
    "statuschange" => "Status has been changed successfully.",
    "imageonly" => "Please upload image only.",
    "sameemail" => "There is already an account with this email address.",
    "loginfirst" => "Please, Login First.",
    "invalidemail" => "Email does not exist. Please try again.",
    "emailsent1" => "Thank you! System sent your email successfully.",
    "pageexist" => "Page name already exists",
    "fileTypeNotSupported" => "File type not supported (Supported file types are JPG,PNG,PDF,DOC,DOCX).",
    "updateProfile" => "Profile has been updated successfully.",
    "updateCProfile" => "Your Company Profile has been updated successfully.",
    "updateAccount" => "Your Account details has been updated successfully.",
    "updateMerchant" => "Venue details has been updated successfully.",
    "addMerchant" => "Your venue information has been submitted.  Funivda will send you a confirmation email once your page has been verfied and added to the site.",
    "inactiveUser" => "Your account is inactive. Please contact administrator.",
    "activeUser" => "Your account has been activated, please login to access your account.",
    "activeaccount" => "Thank you for registering with us. Please check your email to activate your account. If you do not see our email please check your junk folder.",
    "event_add_suc" => "Event added successfully",
    "event_upd_suc" => "Event updated successfully",
    "event_del_suc" => "Event deleted successfully",
    "event_upd_err" => "There is an error in Event updation",
    "event_del_err" => "There is an error in Event deletion.",
    "event_exist" => "Event already exists.",
    "invalid_access" => "You do not have permission to view this page.",
    "invalid_input" => "Invalid access.",
    "invalidCoupon" => "Coupon code is invalid or expired.",
    "validCoupon" => "Coupon has been applied successfully.",
    "subs_succ" => "Thank You! You have successfully subscribed to the plan.",
    "msgsent" => "Message has been sent successfully.",
    "reqsent" => "Request has been sent successfully.",
    "addstatus" => "Status has been posted to your timeline successfully.",
    "acceptreq" => "Contact has been added to your contact list successfully.",
    "rejectreq" => "Contact request has been rejected successfully.",
    "folderexits" => "Folder name already in use. Please use different name.",
    "folderadd" => "Folder has been addedd successfully.",
    "folderupd" => "Folder has been updated successfully.",
    "folderdel" => "Folder has been deleted successfully.",
    "access_denied" => "Invalid access.",
    "error_reg" => "You can not register to the site. Please contact administrator.",
    "documentadd" => "Document has been uploaded successfully.",
    "documentupd" => "Document has been updated successfully.",
    "documentdel" => "Document has been deleted successfully.",
    "limit_err" => "You do not have enough space to upload this document.",
    "invite_contact_succ" => "Invitation has been sent successfully.",
    "invite_contact_fail" => "There is an error in sending Invitation.",
    "sharefile" => "Document has been shared successfully.",
    "unshare" => "Docoment(s) has been unshared successfully.",
    "invsent" => "Invitation has been sent successfully.",
    "expManager" => "Your account has been expired, please renew your subscription.",
    "expEmployee" => "Your account has been expired, please renew your subscription. Contact your manager to renew subscription.",
    "inactiveManager" => "Your account has been expired or inactive.Please contact administrator.",
    "inactiveEmployee" => "Your account has been expired or inactive.Please contact your manager.",
    "company_del_err" => "You cannot delete this company. You have employee(s) associated with this company.",
    "contactdel" => "Contact has been deleted successfully.",
    "sent_err" => "There is an error in sending Invitation.Please try again.",
    "addhours" => "Happy hours has been added successfully.",
    "edithours" => "Happy hours has been updated successfully.",
    "addevent" => "Event has been added successfully.",
    "updateevent" => "Event has been updated successfully.",
    "merchanterr" => "Venue page may not exist yet on the site.  If you are the venue owner you can create your venue page.  If you are not the venue owner you can request that Funvida adds the venue page by clicking the link 'Want a Page Added' at the bottom of the site.",
    "event_del_suc" => "Event has been deleted successfully.",
    "pay_err" => "The transaction could not be processed.",
    "adpay_succ" => "Thank you for your payment. Your venue ad has been created successfully.",
    "evadpay_succ" => "Thank you for your payment. Your event ad has been created successfully.",
    "auth_profile_err" => "There is an error while creatng your Authorize.Net payment profile. Please try again.",
    "favevent_del" => "Event has been deleted from favorite list successfully.",
    "fav_event" => "Event added to your private calendar.",
    "unfav_event" => "Event removed from your private calendar.",
    "eventemailsent" => "Thank you for sharing event.",
    "notisent" => "Thank you! Your email address has been registered with us for updates.",
    "inqsent" => "Thank you for your inquiry. We will contact you soon.",
    "feedsent" => "Thank you for your feedback.",
    "flgsent" => "Thank you for flagging inaccurate information on the site.",
    "clmsent" => "Your page claim request has been submitted.  Funvida will review and get back to you shortly.",
    "wantsent" => "Your request has been sent to us, Funvida will add the page within 1-2 business days.",
    "merchantaddel" => "Your venue ad has been deleted successfully.",
    "eventaddel" => "Event ad has been deleted successfully.",
    "cardup_succ" => "Credit card information has been updated successfully.",
    "cardup_err" => "Please provide correct information.",
    "notactiveUser" => "Please check your e-mail and verify your account before signing in.",
);
?>